/**
 *
 *  Corporations.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/Corporations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::meta_league_dev;

const std::string Corporations::Cols::_id = "id";
const std::string Corporations::Cols::_user_id = "user_id";
const std::string Corporations::Cols::_name = "name";
const std::string Corporations::Cols::_budget = "budget";
const std::string Corporations::Cols::_reputation = "reputation";
const std::string Corporations::Cols::_current_season = "current_season";
const std::string Corporations::Cols::_current_week = "current_week";
const std::string Corporations::Cols::_esports_active = "esports_active";
const std::string Corporations::Cols::_racing_active = "racing_active";
const std::string Corporations::Cols::_tactical_active = "tactical_active";
const std::string Corporations::Cols::_innovation_active = "innovation_active";
const std::string Corporations::Cols::_created_at = "created_at";
const std::string Corporations::Cols::_last_played = "last_played";
const std::string Corporations::primaryKeyName = "id";
const bool Corporations::hasPrimaryKey = true;
const std::string Corporations::tableName = "corporations";

const std::vector<typename Corporations::MetaData> Corporations::metaData_={
{"id","int32_t","int",4,1,1,1},
{"user_id","int32_t","int",4,0,0,1},
{"name","std::string","varchar(100)",100,0,0,1},
{"budget","std::string","decimal(15,2)",0,0,0,0},
{"reputation","int32_t","int",4,0,0,0},
{"current_season","int32_t","int",4,0,0,0},
{"current_week","int32_t","int",4,0,0,0},
{"esports_active","int8_t","tinyint(1)",1,0,0,0},
{"racing_active","int8_t","tinyint(1)",1,0,0,0},
{"tactical_active","int8_t","tinyint(1)",1,0,0,0},
{"innovation_active","int8_t","tinyint(1)",1,0,0,0},
{"created_at","::trantor::Date","timestamp",0,0,0,0},
{"last_played","::trantor::Date","timestamp",0,0,0,0}
};
const std::string &Corporations::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Corporations::Corporations(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["budget"].isNull())
        {
            budget_=std::make_shared<std::string>(r["budget"].as<std::string>());
        }
        if(!r["reputation"].isNull())
        {
            reputation_=std::make_shared<int32_t>(r["reputation"].as<int32_t>());
        }
        if(!r["current_season"].isNull())
        {
            currentSeason_=std::make_shared<int32_t>(r["current_season"].as<int32_t>());
        }
        if(!r["current_week"].isNull())
        {
            currentWeek_=std::make_shared<int32_t>(r["current_week"].as<int32_t>());
        }
        if(!r["esports_active"].isNull())
        {
            esportsActive_=std::make_shared<int8_t>(r["esports_active"].as<int8_t>());
        }
        if(!r["racing_active"].isNull())
        {
            racingActive_=std::make_shared<int8_t>(r["racing_active"].as<int8_t>());
        }
        if(!r["tactical_active"].isNull())
        {
            tacticalActive_=std::make_shared<int8_t>(r["tactical_active"].as<int8_t>());
        }
        if(!r["innovation_active"].isNull())
        {
            innovationActive_=std::make_shared<int8_t>(r["innovation_active"].as<int8_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["last_played"].isNull())
        {
            auto timeStr = r["last_played"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastPlayed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            budget_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            reputation_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            currentSeason_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            currentWeek_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            esportsActive_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            racingActive_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            tacticalActive_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            innovationActive_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastPlayed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Corporations::Corporations(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            budget_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            reputation_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            currentSeason_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            currentWeek_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            esportsActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            racingActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            tacticalActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            innovationActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastPlayed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Corporations::Corporations(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("budget"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["budget"].isNull())
        {
            budget_=std::make_shared<std::string>(pJson["budget"].asString());
        }
    }
    if(pJson.isMember("reputation"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["reputation"].isNull())
        {
            reputation_=std::make_shared<int32_t>((int32_t)pJson["reputation"].asInt64());
        }
    }
    if(pJson.isMember("current_season"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["current_season"].isNull())
        {
            currentSeason_=std::make_shared<int32_t>((int32_t)pJson["current_season"].asInt64());
        }
    }
    if(pJson.isMember("current_week"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["current_week"].isNull())
        {
            currentWeek_=std::make_shared<int32_t>((int32_t)pJson["current_week"].asInt64());
        }
    }
    if(pJson.isMember("esports_active"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["esports_active"].isNull())
        {
            esportsActive_=std::make_shared<int8_t>((int8_t)pJson["esports_active"].asInt64());
        }
    }
    if(pJson.isMember("racing_active"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["racing_active"].isNull())
        {
            racingActive_=std::make_shared<int8_t>((int8_t)pJson["racing_active"].asInt64());
        }
    }
    if(pJson.isMember("tactical_active"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["tactical_active"].isNull())
        {
            tacticalActive_=std::make_shared<int8_t>((int8_t)pJson["tactical_active"].asInt64());
        }
    }
    if(pJson.isMember("innovation_active"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["innovation_active"].isNull())
        {
            innovationActive_=std::make_shared<int8_t>((int8_t)pJson["innovation_active"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_played"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["last_played"].isNull())
        {
            auto timeStr = pJson["last_played"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastPlayed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Corporations::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            budget_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            reputation_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            currentSeason_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            currentWeek_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            esportsActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            racingActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            tacticalActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            innovationActive_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastPlayed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Corporations::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("budget"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["budget"].isNull())
        {
            budget_=std::make_shared<std::string>(pJson["budget"].asString());
        }
    }
    if(pJson.isMember("reputation"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["reputation"].isNull())
        {
            reputation_=std::make_shared<int32_t>((int32_t)pJson["reputation"].asInt64());
        }
    }
    if(pJson.isMember("current_season"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["current_season"].isNull())
        {
            currentSeason_=std::make_shared<int32_t>((int32_t)pJson["current_season"].asInt64());
        }
    }
    if(pJson.isMember("current_week"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["current_week"].isNull())
        {
            currentWeek_=std::make_shared<int32_t>((int32_t)pJson["current_week"].asInt64());
        }
    }
    if(pJson.isMember("esports_active"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["esports_active"].isNull())
        {
            esportsActive_=std::make_shared<int8_t>((int8_t)pJson["esports_active"].asInt64());
        }
    }
    if(pJson.isMember("racing_active"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["racing_active"].isNull())
        {
            racingActive_=std::make_shared<int8_t>((int8_t)pJson["racing_active"].asInt64());
        }
    }
    if(pJson.isMember("tactical_active"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["tactical_active"].isNull())
        {
            tacticalActive_=std::make_shared<int8_t>((int8_t)pJson["tactical_active"].asInt64());
        }
    }
    if(pJson.isMember("innovation_active"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["innovation_active"].isNull())
        {
            innovationActive_=std::make_shared<int8_t>((int8_t)pJson["innovation_active"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_played"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["last_played"].isNull())
        {
            auto timeStr = pJson["last_played"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastPlayed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &Corporations::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Corporations::getId() const noexcept
{
    return id_;
}
void Corporations::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Corporations::PrimaryKeyType & Corporations::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Corporations::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Corporations::getUserId() const noexcept
{
    return userId_;
}
void Corporations::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[1] = true;
}

const std::string &Corporations::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Corporations::getName() const noexcept
{
    return name_;
}
void Corporations::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[2] = true;
}
void Corporations::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[2] = true;
}

const std::string &Corporations::getValueOfBudget() const noexcept
{
    static const std::string defaultValue = std::string();
    if(budget_)
        return *budget_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Corporations::getBudget() const noexcept
{
    return budget_;
}
void Corporations::setBudget(const std::string &pBudget) noexcept
{
    budget_ = std::make_shared<std::string>(pBudget);
    dirtyFlag_[3] = true;
}
void Corporations::setBudget(std::string &&pBudget) noexcept
{
    budget_ = std::make_shared<std::string>(std::move(pBudget));
    dirtyFlag_[3] = true;
}
void Corporations::setBudgetToNull() noexcept
{
    budget_.reset();
    dirtyFlag_[3] = true;
}

const int32_t &Corporations::getValueOfReputation() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(reputation_)
        return *reputation_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Corporations::getReputation() const noexcept
{
    return reputation_;
}
void Corporations::setReputation(const int32_t &pReputation) noexcept
{
    reputation_ = std::make_shared<int32_t>(pReputation);
    dirtyFlag_[4] = true;
}
void Corporations::setReputationToNull() noexcept
{
    reputation_.reset();
    dirtyFlag_[4] = true;
}

const int32_t &Corporations::getValueOfCurrentSeason() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(currentSeason_)
        return *currentSeason_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Corporations::getCurrentSeason() const noexcept
{
    return currentSeason_;
}
void Corporations::setCurrentSeason(const int32_t &pCurrentSeason) noexcept
{
    currentSeason_ = std::make_shared<int32_t>(pCurrentSeason);
    dirtyFlag_[5] = true;
}
void Corporations::setCurrentSeasonToNull() noexcept
{
    currentSeason_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &Corporations::getValueOfCurrentWeek() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(currentWeek_)
        return *currentWeek_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Corporations::getCurrentWeek() const noexcept
{
    return currentWeek_;
}
void Corporations::setCurrentWeek(const int32_t &pCurrentWeek) noexcept
{
    currentWeek_ = std::make_shared<int32_t>(pCurrentWeek);
    dirtyFlag_[6] = true;
}
void Corporations::setCurrentWeekToNull() noexcept
{
    currentWeek_.reset();
    dirtyFlag_[6] = true;
}

const int8_t &Corporations::getValueOfEsportsActive() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(esportsActive_)
        return *esportsActive_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Corporations::getEsportsActive() const noexcept
{
    return esportsActive_;
}
void Corporations::setEsportsActive(const int8_t &pEsportsActive) noexcept
{
    esportsActive_ = std::make_shared<int8_t>(pEsportsActive);
    dirtyFlag_[7] = true;
}
void Corporations::setEsportsActiveToNull() noexcept
{
    esportsActive_.reset();
    dirtyFlag_[7] = true;
}

const int8_t &Corporations::getValueOfRacingActive() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(racingActive_)
        return *racingActive_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Corporations::getRacingActive() const noexcept
{
    return racingActive_;
}
void Corporations::setRacingActive(const int8_t &pRacingActive) noexcept
{
    racingActive_ = std::make_shared<int8_t>(pRacingActive);
    dirtyFlag_[8] = true;
}
void Corporations::setRacingActiveToNull() noexcept
{
    racingActive_.reset();
    dirtyFlag_[8] = true;
}

const int8_t &Corporations::getValueOfTacticalActive() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(tacticalActive_)
        return *tacticalActive_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Corporations::getTacticalActive() const noexcept
{
    return tacticalActive_;
}
void Corporations::setTacticalActive(const int8_t &pTacticalActive) noexcept
{
    tacticalActive_ = std::make_shared<int8_t>(pTacticalActive);
    dirtyFlag_[9] = true;
}
void Corporations::setTacticalActiveToNull() noexcept
{
    tacticalActive_.reset();
    dirtyFlag_[9] = true;
}

const int8_t &Corporations::getValueOfInnovationActive() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(innovationActive_)
        return *innovationActive_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Corporations::getInnovationActive() const noexcept
{
    return innovationActive_;
}
void Corporations::setInnovationActive(const int8_t &pInnovationActive) noexcept
{
    innovationActive_ = std::make_shared<int8_t>(pInnovationActive);
    dirtyFlag_[10] = true;
}
void Corporations::setInnovationActiveToNull() noexcept
{
    innovationActive_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &Corporations::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Corporations::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Corporations::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[11] = true;
}
void Corporations::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &Corporations::getValueOfLastPlayed() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastPlayed_)
        return *lastPlayed_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Corporations::getLastPlayed() const noexcept
{
    return lastPlayed_;
}
void Corporations::setLastPlayed(const ::trantor::Date &pLastPlayed) noexcept
{
    lastPlayed_ = std::make_shared<::trantor::Date>(pLastPlayed);
    dirtyFlag_[12] = true;
}
void Corporations::setLastPlayedToNull() noexcept
{
    lastPlayed_.reset();
    dirtyFlag_[12] = true;
}

void Corporations::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Corporations::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "name",
        "budget",
        "reputation",
        "current_season",
        "current_week",
        "esports_active",
        "racing_active",
        "tactical_active",
        "innovation_active",
        "created_at",
        "last_played"
    };
    return inCols;
}

void Corporations::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getBudget())
        {
            binder << getValueOfBudget();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getReputation())
        {
            binder << getValueOfReputation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCurrentSeason())
        {
            binder << getValueOfCurrentSeason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCurrentWeek())
        {
            binder << getValueOfCurrentWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEsportsActive())
        {
            binder << getValueOfEsportsActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRacingActive())
        {
            binder << getValueOfRacingActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTacticalActive())
        {
            binder << getValueOfTacticalActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getInnovationActive())
        {
            binder << getValueOfInnovationActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLastPlayed())
        {
            binder << getValueOfLastPlayed();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Corporations::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void Corporations::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getBudget())
        {
            binder << getValueOfBudget();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getReputation())
        {
            binder << getValueOfReputation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCurrentSeason())
        {
            binder << getValueOfCurrentSeason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCurrentWeek())
        {
            binder << getValueOfCurrentWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEsportsActive())
        {
            binder << getValueOfEsportsActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRacingActive())
        {
            binder << getValueOfRacingActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTacticalActive())
        {
            binder << getValueOfTacticalActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getInnovationActive())
        {
            binder << getValueOfInnovationActive();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLastPlayed())
        {
            binder << getValueOfLastPlayed();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Corporations::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getBudget())
    {
        ret["budget"]=getValueOfBudget();
    }
    else
    {
        ret["budget"]=Json::Value();
    }
    if(getReputation())
    {
        ret["reputation"]=getValueOfReputation();
    }
    else
    {
        ret["reputation"]=Json::Value();
    }
    if(getCurrentSeason())
    {
        ret["current_season"]=getValueOfCurrentSeason();
    }
    else
    {
        ret["current_season"]=Json::Value();
    }
    if(getCurrentWeek())
    {
        ret["current_week"]=getValueOfCurrentWeek();
    }
    else
    {
        ret["current_week"]=Json::Value();
    }
    if(getEsportsActive())
    {
        ret["esports_active"]=getValueOfEsportsActive();
    }
    else
    {
        ret["esports_active"]=Json::Value();
    }
    if(getRacingActive())
    {
        ret["racing_active"]=getValueOfRacingActive();
    }
    else
    {
        ret["racing_active"]=Json::Value();
    }
    if(getTacticalActive())
    {
        ret["tactical_active"]=getValueOfTacticalActive();
    }
    else
    {
        ret["tactical_active"]=Json::Value();
    }
    if(getInnovationActive())
    {
        ret["innovation_active"]=getValueOfInnovationActive();
    }
    else
    {
        ret["innovation_active"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getLastPlayed())
    {
        ret["last_played"]=getLastPlayed()->toDbStringLocal();
    }
    else
    {
        ret["last_played"]=Json::Value();
    }
    return ret;
}

std::string Corporations::toString() const
{
    return toJson().toStyledString();
}

Json::Value Corporations::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[2]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getBudget())
            {
                ret[pMasqueradingVector[3]]=getValueOfBudget();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getReputation())
            {
                ret[pMasqueradingVector[4]]=getValueOfReputation();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCurrentSeason())
            {
                ret[pMasqueradingVector[5]]=getValueOfCurrentSeason();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCurrentWeek())
            {
                ret[pMasqueradingVector[6]]=getValueOfCurrentWeek();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getEsportsActive())
            {
                ret[pMasqueradingVector[7]]=getValueOfEsportsActive();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getRacingActive())
            {
                ret[pMasqueradingVector[8]]=getValueOfRacingActive();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getTacticalActive())
            {
                ret[pMasqueradingVector[9]]=getValueOfTacticalActive();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getInnovationActive())
            {
                ret[pMasqueradingVector[10]]=getValueOfInnovationActive();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[11]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getLastPlayed())
            {
                ret[pMasqueradingVector[12]]=getLastPlayed()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getBudget())
    {
        ret["budget"]=getValueOfBudget();
    }
    else
    {
        ret["budget"]=Json::Value();
    }
    if(getReputation())
    {
        ret["reputation"]=getValueOfReputation();
    }
    else
    {
        ret["reputation"]=Json::Value();
    }
    if(getCurrentSeason())
    {
        ret["current_season"]=getValueOfCurrentSeason();
    }
    else
    {
        ret["current_season"]=Json::Value();
    }
    if(getCurrentWeek())
    {
        ret["current_week"]=getValueOfCurrentWeek();
    }
    else
    {
        ret["current_week"]=Json::Value();
    }
    if(getEsportsActive())
    {
        ret["esports_active"]=getValueOfEsportsActive();
    }
    else
    {
        ret["esports_active"]=Json::Value();
    }
    if(getRacingActive())
    {
        ret["racing_active"]=getValueOfRacingActive();
    }
    else
    {
        ret["racing_active"]=Json::Value();
    }
    if(getTacticalActive())
    {
        ret["tactical_active"]=getValueOfTacticalActive();
    }
    else
    {
        ret["tactical_active"]=Json::Value();
    }
    if(getInnovationActive())
    {
        ret["innovation_active"]=getValueOfInnovationActive();
    }
    else
    {
        ret["innovation_active"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getLastPlayed())
    {
        ret["last_played"]=getLastPlayed()->toDbStringLocal();
    }
    else
    {
        ret["last_played"]=Json::Value();
    }
    return ret;
}

bool Corporations::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("budget"))
    {
        if(!validJsonOfField(3, "budget", pJson["budget"], err, true))
            return false;
    }
    if(pJson.isMember("reputation"))
    {
        if(!validJsonOfField(4, "reputation", pJson["reputation"], err, true))
            return false;
    }
    if(pJson.isMember("current_season"))
    {
        if(!validJsonOfField(5, "current_season", pJson["current_season"], err, true))
            return false;
    }
    if(pJson.isMember("current_week"))
    {
        if(!validJsonOfField(6, "current_week", pJson["current_week"], err, true))
            return false;
    }
    if(pJson.isMember("esports_active"))
    {
        if(!validJsonOfField(7, "esports_active", pJson["esports_active"], err, true))
            return false;
    }
    if(pJson.isMember("racing_active"))
    {
        if(!validJsonOfField(8, "racing_active", pJson["racing_active"], err, true))
            return false;
    }
    if(pJson.isMember("tactical_active"))
    {
        if(!validJsonOfField(9, "tactical_active", pJson["tactical_active"], err, true))
            return false;
    }
    if(pJson.isMember("innovation_active"))
    {
        if(!validJsonOfField(10, "innovation_active", pJson["innovation_active"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("last_played"))
    {
        if(!validJsonOfField(12, "last_played", pJson["last_played"], err, true))
            return false;
    }
    return true;
}
bool Corporations::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Corporations::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("budget"))
    {
        if(!validJsonOfField(3, "budget", pJson["budget"], err, false))
            return false;
    }
    if(pJson.isMember("reputation"))
    {
        if(!validJsonOfField(4, "reputation", pJson["reputation"], err, false))
            return false;
    }
    if(pJson.isMember("current_season"))
    {
        if(!validJsonOfField(5, "current_season", pJson["current_season"], err, false))
            return false;
    }
    if(pJson.isMember("current_week"))
    {
        if(!validJsonOfField(6, "current_week", pJson["current_week"], err, false))
            return false;
    }
    if(pJson.isMember("esports_active"))
    {
        if(!validJsonOfField(7, "esports_active", pJson["esports_active"], err, false))
            return false;
    }
    if(pJson.isMember("racing_active"))
    {
        if(!validJsonOfField(8, "racing_active", pJson["racing_active"], err, false))
            return false;
    }
    if(pJson.isMember("tactical_active"))
    {
        if(!validJsonOfField(9, "tactical_active", pJson["tactical_active"], err, false))
            return false;
    }
    if(pJson.isMember("innovation_active"))
    {
        if(!validJsonOfField(10, "innovation_active", pJson["innovation_active"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("last_played"))
    {
        if(!validJsonOfField(12, "last_played", pJson["last_played"], err, false))
            return false;
    }
    return true;
}
bool Corporations::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Corporations::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
